apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "s3perf-tester.fullname" . }}
  labels:
    {{- include "s3perf-tester.labels" . | nindent 4 }}
data:
  REGION: {{ .Values.conf.s3.region | b64enc | quote }}
  HOST: {{ .Values.conf.s3.host | b64enc | quote }}
  BUCKET: {{ .Values.conf.s3.bucket | b64enc | quote }}
  ACCESS_KEY: {{ .Values.conf.s3.access_key | b64enc | quote }}
  SECRET_KEY: {{ .Values.conf.s3.secret_key | b64enc | quote }}
  FILE_SIZE_KB: {{ printf "%d" .Values.conf.file_size_kb | b64enc | quote }}
  PROCESSES: {{ printf "%d" .Values.processCount | b64enc | quote }}
